# Generated by Django 4.1.1 on 2022-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
